FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY training ./training

ENV MLFLOW_TRACKING_URI=http://mlflow:5000

CMD ["python", "training/train.py"]
